version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/node:14.17.1
    steps:
      - checkout
      - run:
          name: run build
          command: "npm run build"
  test:
    docker:
      - image: cimg/node:14.17.1
    steps:
      - checkout
      - run:
          name: run tests
          command: "npm run test"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
